services:
  php:
    image: yiisoftware/yii2-php:8.4-fpm-nginx
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      db:
        condition: service_healthy
    env_file: .env

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-yii2basic}
      MYSQL_USER: ${DB_USER:-yii2}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
    ports:
      - '33060:3306'
    volumes:
      - ./db-data:/var/lib/mysql
    env_file: .env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u$DB_USER", "-p$DB_PASSWORD"]
      timeout: 5s
      retries: 10
      interval: 5s

  queue:
    image: yiisoftware/yii2-php:8.4-fpm-nginx
    volumes:
      - ./:/app:delegated
    restart: on-failure
    environment:
      - SMS_API_KEY=${SMS_API_KEY:-MOCK_KEY}
    command: ["php", "-d", "opcache.enable_cli=0", "yii", "queue/listen", "--verbose=1", "--color=0"]
    depends_on:
      db:
        condition: service_healthy
    env_file: .env