meta:
  title: 'HTTP Routes'
routes:
  -
    path: /
    action: site/index
    controller: SiteController
    methods:
      - GET
    guards:
      - Auth
  -
    path: /api/v1/books
    action: api/v1/book/index
    controller: api/v1/BookController
    methods:
      - GET
  -
    path: /author
    action: author/index
    controller: AuthorController
    methods:
      - GET
    guards:
      - Auth
  -
    path: /author/create
    action: author/create
    controller: AuthorController
    methods:
      - GET
      - POST
    guards:
      - Idempotency
      - Auth
  -
    path: /author/delete
    action: author/delete
    controller: AuthorController
    methods:
      - POST
    guards:
      - Idempotency
      - Auth
  -
    path: /author/search
    action: author/search
    controller: AuthorController
    methods:
      - GET
    guards:
      - Auth
  -
    path: /author/update
    action: author/update
    controller: AuthorController
    methods:
      - GET
      - POST
    guards:
      - Idempotency
      - Auth
  -
    path: /author/view
    action: author/view
    controller: AuthorController
    methods:
      - GET
    guards:
      - Auth
  -
    path: /book
    action: book/index
    controller: BookController
    methods:
      - GET
    guards:
      - Auth
  -
    path: /book/archive
    action: book/archive
    controller: BookController
    methods:
      - POST
    guards:
      - Idempotency
      - Auth
  -
    path: /book/create
    action: book/create
    controller: BookController
    methods:
      - GET
      - POST
    guards:
      - Idempotency
      - Auth
  -
    path: /book/delete
    action: book/delete
    controller: BookController
    methods:
      - POST
    guards:
      - Idempotency
      - Auth
  -
    path: /book/publish
    action: book/publish
    controller: BookController
    methods:
      - POST
    guards:
      - Idempotency
      - Auth
  -
    path: /book/restore
    action: book/restore
    controller: BookController
    methods:
      - POST
    guards:
      - Idempotency
      - Auth
  -
    path: /book/unpublish
    action: book/unpublish
    controller: BookController
    methods:
      - POST
    guards:
      - Idempotency
      - Auth
  -
    path: /book/update
    action: book/update
    controller: BookController
    methods:
      - GET
      - POST
    guards:
      - Idempotency
      - Auth
  -
    path: /book/view
    action: book/view
    controller: BookController
    methods:
      - GET
    guards:
      - Auth
  -
    path: /health
    action: health/index
    controller: HealthController
    methods:
      - GET
  -
    path: /report
    action: report/index
    controller: ReportController
    methods:
      - GET
  -
    path: /site/api
    action: site/api
    controller: SiteController
    methods:
      - GET
    guards:
      - Auth
  -
    path: /site/login
    action: site/login
    controller: SiteController
    methods:
      - GET
      - POST
    guards:
      - Auth
  -
    path: /site/logout
    action: site/logout
    controller: SiteController
    methods:
      - POST
    guards:
      - Auth
  -
    path: /subscription/form
    action: subscription/form
    controller: SubscriptionController
    methods:
      - GET
  -
    path: /subscription/subscribe
    action: subscription/subscribe
    controller: SubscriptionController
    methods:
      - POST
    guards:
      - Idempotency
