meta:
  title: "HTTP Routes"
  source: "generated"
  updated_at: "2026-01-01T16:46:49+00:00"

routes:
  - path: "/"
    action: "site/index"
    controller: "SiteController"
    methods:
      - "GET"
    alias: "/site/index"
  - path: "/author/create"
    action: "author/create"
    controller: "AuthorController"
    methods:
      - "GET"
      - "POST"
  - path: "/author/delete"
    action: "author/delete"
    controller: "AuthorController"
    methods:
      - "GET"
  - path: "/author/index"
    action: "author/index"
    controller: "AuthorController"
    methods:
      - "GET"
  - path: "/author/search"
    action: "author/search"
    controller: "AuthorController"
    methods:
      - "GET"
  - path: "/author/update"
    action: "author/update"
    controller: "AuthorController"
    methods:
      - "GET"
      - "POST"
  - path: "/author/view"
    action: "author/view"
    controller: "AuthorController"
    methods:
      - "GET"
  - path: "/book/create"
    action: "book/create"
    controller: "BookController"
    methods:
      - "GET"
      - "POST"
  - path: "/book/delete"
    action: "book/delete"
    controller: "BookController"
    methods:
      - "GET"
  - path: "/book/index"
    action: "book/index"
    controller: "BookController"
    methods:
      - "GET"
  - path: "/book/index"
    action: "book/index"
    controller: "BookController"
    methods:
      - "GET"
  - path: "/book/publish"
    action: "book/publish"
    controller: "BookController"
    methods:
      - "GET"
  - path: "/book/update"
    action: "book/update"
    controller: "BookController"
    methods:
      - "GET"
      - "POST"
  - path: "/book/view"
    action: "book/view"
    controller: "BookController"
    methods:
      - "GET"
  - path: "/report/index"
    action: "report/index"
    controller: "ReportController"
    methods:
      - "GET"
  - path: "/site/api"
    action: "site/api"
    controller: "SiteController"
    methods:
      - "GET"
  - path: "/site/login"
    action: "site/login"
    controller: "SiteController"
    methods:
      - "GET"
      - "POST"
  - path: "/site/logout"
    action: "site/logout"
    controller: "SiteController"
    methods:
      - "GET"
  - path: "/subscription/form"
    action: "subscription/form"
    controller: "SubscriptionController"
    methods:
      - "GET"
  - path: "/subscription/subscribe"
    action: "subscription/subscribe"
    controller: "SubscriptionController"
    methods:
      - "GET"
