meta:
  title: 'HTTP Routes'
  updated_at: '2026-01-09T07:06:13+00:00'
routes:
  -
    path: /
    action: site/index
    controller: SiteController
    methods:
      - GET
    guards:
      - Auth
  -
    path: /author/create
    action: author/create
    controller: AuthorController
    methods:
      - GET
      - POST
    guards:
      - Idempotency
      - Auth
  -
    path: /author/delete
    action: author/delete
    controller: AuthorController
    methods:
      - GET
    guards:
      - Idempotency
      - Auth
  -
    path: /author/index
    action: author/index
    controller: AuthorController
    methods:
      - GET
    guards:
      - Idempotency
      - Auth
  -
    path: /author/search
    action: author/search
    controller: AuthorController
    methods:
      - GET
    guards:
      - Idempotency
      - Auth
  -
    path: /author/update
    action: author/update
    controller: AuthorController
    methods:
      - GET
      - POST
    guards:
      - Idempotency
      - Auth
  -
    path: /author/view
    action: author/view
    controller: AuthorController
    methods:
      - GET
    guards:
      - Idempotency
      - Auth
  -
    path: /book/create
    action: book/create
    controller: BookController
    methods:
      - GET
      - POST
    guards:
      - Idempotency
      - Auth
  -
    path: /book/delete
    action: book/delete
    controller: BookController
    methods:
      - GET
    guards:
      - Idempotency
      - Auth
  -
    path: /book/index
    action: book/index
    controller: BookController
    methods:
      - GET
    guards:
      - Idempotency
      - Auth
  -
    path: /book/index
    action: book/index
    controller: BookController
    methods:
      - GET
    guards:
      - Idempotency
      - Auth
  -
    path: /book/publish
    action: book/publish
    controller: BookController
    methods:
      - GET
    guards:
      - Idempotency
      - Auth
  -
    path: /book/update
    action: book/update
    controller: BookController
    methods:
      - GET
      - POST
    guards:
      - Idempotency
      - Auth
  -
    path: /book/view
    action: book/view
    controller: BookController
    methods:
      - GET
    guards:
      - Idempotency
      - Auth
  -
    path: /report/index
    action: report/index
    controller: ReportController
    methods:
      - GET
  -
    path: /site/api
    action: site/api
    controller: SiteController
    methods:
      - GET
    guards:
      - Auth
  -
    path: /site/login
    action: site/login
    controller: SiteController
    methods:
      - GET
      - POST
    guards:
      - Auth
  -
    path: /site/logout
    action: site/logout
    controller: SiteController
    methods:
      - GET
    guards:
      - Auth
  -
    path: /subscription/form
    action: subscription/form
    controller: SubscriptionController
    methods:
      - GET
    guards:
      - Idempotency
      - Auth
  -
    path: /subscription/subscribe
    action: subscription/subscribe
    controller: SubscriptionController
    methods:
      - GET
    guards:
      - Idempotency
      - Auth
